language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-add-repository --yes ppa:zoogie/sdl2-snapshots       # libsdl2
  - export PATH=~/usr/bin:$PATH

install:
  - sudo apt-get update -qq


before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - clang
    - libsdl2-dev
    - libsdl2-image-dev
    - libglew-dev
