language: generic
os: osx

compiler: gcc

matrix:
    include:
      - os: linux
        env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
        before_install:
          - sudo apt-add-repository --yes ppa:zoogie/sdl2-snapshots       # libsdl2

        install:
          - sudo apt-get update -qq
          - sudo apt-get install -q -y libsdl2-dev libsdl2-image-dev

        addons:
          apt:
            sources:
            - ubuntu-toolchain-r-test
            packages:
            - gcc-5
            - g++-5
            - libglew-dev

before_install:
    - brew install glew
    - brew install sdl2
    - brew install sdl2_image

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
