language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get install libsdl2-2.0-0 libsdl2-dev libsdl2-image-2.0-0 libsdl2-image-dev



before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
