language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test     # newer toolchain
  - sudo apt-add-repository --yes ppa:zoogie/sdl2-snapshots       # libsdl2
  - export PATH=~/usr/bin:$PATH

install:
  - sudo apt-get update -qq
  - sudo apt-get install -q -y libsdl2-dev libsdl2-image-dev
  - sudo apt-get install -q -y libglew libglew-dev


before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
